# Generated by Django 5.2.6 on 2025-09-15 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=5)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, help_text='Desmarque este campo para parar a veiculação')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=5)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.CharField(max_length=50)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lowprice.product')),
            ],
        ),
    ]
