# Generated by Django 5.2.6 on 2025-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowprice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update_date',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
