# Generated by Django 5.2.6 on 2025-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowprice', '0004_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Completo'), ('FAILED', 'Falhou')], default='PENDING', max_length=20),
        ),
    ]
