# Generated by Django 5.2.7 on 2025-10-03 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowprice', '0005_search_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_status', to='lowprice.search')),
            ],
        ),
    ]
