# Generated by Django 5.2.7 on 2025-10-15 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowprice', '0006_searchsitestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='lowprice.product'),
        ),
    ]
