services:
  djangoapp:
    container_name: djangoapp_lowprice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis
    # Diz ao entrypoint para executar o bloco "web"
    command: ['web']

  psql:
    container_name: psql_lowprice
    image: postgres:17-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - '5433:5432'

  redis:
    container_name: redis_lowprice
    image: 'redis:7-alpine'

  celery_worker:
    container_name: worker_lowprice
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./djangoapp:/djangoapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - djangoapp
      - redis
    # Diz ao entrypoint para executar o bloco "worker"
    command: ['worker']
